[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    # 0.96" SSD1306 128x64 two-color OLED.
    # If the display stays blank, swap SDA and SCL values.
    -DOLED_SDA=20
    -DOLED_SCL=21

lib_deps =
    olikraus/U8g2